module.exports = {
  mode:"development",
  entry:{
    day1:'./toy-react/day1/index.js',
    day2:'./toy-react/day2/index.js',
    day3:'./toy-react/day3/index.js'
  },
  module:{
    rules:[
      {
        test:/\.js$/,
        use:{
          loader:'babel-loader',
          options:{
            presets:['@babel/preset-env'],
            plugins:[
              ['@babel/plugin-transform-react-jsx',
              {pragma:'createElement'}]
            ]
          }
        }
      }
    ]
  },
  optimization:{
    minimize:false
  }
}